name: Dependent Jobs Workflow

on:
  workflow_dispatch:

jobs:
  Fetch-and-Store-Data-Spinnaker-API:
    runs-on: ubuntu-latest
#     description: This is Job A
    steps:
      - name: Job A
        run: echo "Job A"

  Run-Script-on-Data:
    runs-on: ubuntu-latest
    needs: Fetch-and-Store-Data-Spinnaker-API
    steps:
      - name: Job B
        run: echo "Job B"

  Get-User-Email-Github-API:
    runs-on: ubuntu-latest
    needs: Fetch-and-Store-Data-Spinnaker-API
    steps:
      - name: Job C
        run: echo "Job C"

  SNS-Notification:
    runs-on: ubuntu-latest
    needs: Get-User-Email-Github-API
    steps:
      - name: Job D
        run: echo "Job D"
