name: Slack Notification Demo
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  slackNotification:
    name: Slack Notification Demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification Demo
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
        SLACK_MESSAGE: 'Demoing the Slack Notification'
        SLACK_TITLE: 'Slack Notification Demo'
